// Code generated by Thrift Compiler (0.20.0). DO NOT EDIT.

package impalaservice

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"github.com/abdelaziz-ouhammou/go-impala/services/beeswax"
	"github.com/abdelaziz-ouhammou/go-impala/services/cli_service"
	"github.com/abdelaziz-ouhammou/go-impala/services/status"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"log/slog"
	"regexp"
	"strings"
	"time"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

var _ = status.GoUnusedProtection__
var _ = beeswax.GoUnusedProtection__
var _ = cli_service.GoUnusedProtection__
var DEFAULT_QUERY_OPTIONS map[TImpalaQueryOptions]string

func init() {
	DEFAULT_QUERY_OPTIONS = map[TImpalaQueryOptions]string{
		0:  "false",
		9:  "false",
		3:  "0",
		11: "",
		10: "-1",
		2:  "false",
		1:  "0",
		7:  "0",
		6:  "0",
		4:  "0",
		5:  "0",
		8:  "0",
	}

}
